Feature: Validate the reference of descriptors when creating resources

        Background
            Given this student exists:
                  | studentUniqueId | birthDate  | firstName | lastSurname |
                  | 604824          | 2010-01-13 | Traci     | Mathews     |


        @ignore
        Scenario: User CAN'T create a resource when descriptor doesn't exist
             When a POST request is made to "/ed-fi/localEducationAgencies" with
                  """
                  {
                        "localEducationAgencyId": 25590100,
                        "nameOfInstitution": "Grand+Institution+Test",
                        "categories": [
                            {
                              "educationOrganizationCategoryDescriptor": "uri://ed-fi.org/EducationOrganizationCategoryDescriptor#Fake"
                            }
                        ],
                        "localEducationAgencyCategoryDescriptor": "uri://ed-fi.org/LocalEducationAgencyCategoryDescriptor#Fake"
                  }
                  """
             Then it should respond with 400
              And the response body is
                  """
                  {"detail":"Data validation failed. See 'validationErrors' for details.","type":"urn:ed-fi:api:bad-request:data","title":"Data Validation Failed","status":400,"correlationId":null,"validationErrors":{"$.localEducationAgencyCategoryDescriptor":["LocalEducationAgencyCategoryDescriptor value 'uri://ed-fi.org/LocalEducationAgencyCategoryDescriptor#Fake' does not exist."],"$.categories[0].educationOrganizationCategoryDescriptor":["EducationOrganizationCategoryDescriptor value 'uri://ed-fi.org/EducationOrganizationCategoryDescriptor#Fake' does not exist."]}}
                  """

        @ignore
        Scenario: User can POST a resource when descriptor exists
             When a POST request is made to "/ed-fi/localEducationAgencies" with
                  """
                  {
                    "localEducationAgencyId": 25590100,
                    "nameOfInstitution": "Grand Institution Test",
                    "categories": [
                        {
                            "educationOrganizationCategoryDescriptor": "uri://ed-fi.org/EducationOrganizationCategoryDescriptor#Education+Service+Center"
                        }
                    ],
                    "localEducationAgencyCategoryDescriptor": "uri://ed-fi.org/LocalEducationAgencyCategoryDescriptor#Public+school+district+part+of+a+supervisory+union"
                  }
                  """
             Then it should respond with 201


        @ignore
        Scenario: User can UPDATE a resource when descriptor exists
             When a PUT request is made to "/ed-fi/students/{id}" with
                  """
                  {
                    "id": "{id}"
                    "studentUniqueId": "604824",
                    "birthDate": "2010-01-13",
                    "firstName": "Traci",
                    "lastSurname": "Mathews",
                    "citizenshipStatusDescriptor": "uri://ed-fi.org/CitizenshipStatusDescriptor#US+Citizen"
                  }
                  """
             Then it should respond with 204


        @ignore
        Scenario: User CANNOT update a resource using a descriptor that does not exist
             When a PUT request is made to "/ed-fi/students/{id}" with
                  """
                  {
                    "id": "{id}"
                    "studentUniqueId": "123456789",
                    "birthDate": "2010-03-25",
                    "firstName": "Jeff",
                    "lastSurname": "Test"
                    "citizenshipStatusDescriptor": "uri://ed-fi.org/CitizenshipStatusDescriptor#Fake",
                  """
             Then it should respond with 400
              And the response body is
                  """
                  {
                    "detail": "Data validation failed. See 'validationErrors' for details.",
                    "type": "urn:ed-fi:api:bad-request:data",
                    "title": "Data Validation Failed",
                    "status": 400,
                    "correlationId": null,
                    "validationErrors": {
                        "$.citizenshipStatusDescriptor": [
                            "CitizenshipStatusDescriptor value 'uri://ed-fi.org/CitizenshipStatusDescriptor#Fake' does not exist."
                        ]
                    }
                  }
                  """

        @ignore
        Scenario: User CANNOT create (upsert) a resource using a descriptor that does not exist
             When a POST request is made to "/ed-fi/students" with
                  """
                  {
                    "studentUniqueId": "604824",
                    "birthDate": "2010-01-13",
                    "firstName": "Traci",
                    "lastSurname": "Mathews",
                    "citizenshipStatusDescriptor": "uri://ed-fi.org/CitizenshipStatusDescriptor#Fake"
                  }
                  """
             Then it should respond with 400
              And the response body is
                  """
                  {
                    "detail": "Data validation failed. See 'validationErrors' for details.",
                    "type": "urn:ed-fi:api:bad-request:data",
                    "title": "Data Validation Failed",
                    "status": 400,
                    "correlationId": null,
                    "validationErrors": {
                        "$.citizenshipStatusDescriptor": [
                            "CitizenshipStatusDescriptor value 'uri://ed-fi.org/CitizenshipStatusDescriptor#Fake' does not exist."
                        ]
                    }
                  }
                  """
